### ISSUE TITLE
Existing files/dirs while building are not cleaned

### ISSUE THREAD

**Issue by lukaszstolarczuk** [pmem/pmdk-convert#53]
When building pmdk-convert in the same folder it does not clean old data/files (at least sub-directory nvml-1.5) and even if there's a change in there, it won't appear and may cause errors (like it did around 1.5.1-rc4, when we've changed badblock source files)

**Comment by kilobyte** [comment]
There would need to be a way to suppress such "cleaning" — while re-fetching the tarballs is acceptable for an individual user, distributions require self-contained packages that build without external network access.  It would also interfere with reproducibly building past versions.

**Comment by marcinslusarz** [comment]
This is fixed with https://github.com/pmem/pmdk-convert/pull/66/commits/5365e580b357e3f9bac201daed1d7a039ded3af4.
I believe it doesn't interfere with the way distribution packages are built.
