### ISSUE TITLE
Release 1.8

### ISSUE THREAD

**Issue by nmorey** [pmem/pmdk-convert#82]
When is the 1.8 release planned ?
pmdk 1.8 has been out for a month now and it seems the work has already been done in pmdk-convert for 1.8 support.
Is there something blocking ? Or just a tag missing ?

**Comment by marcinslusarz** [comment]
PMDK 1.8 didn't introduce any on-media layout changes, so there's no need for pmdk-convert 1.8. I should have mentioned this in the 1.8 announcement. Sorry about that.

The support for pmdk 1.8 in pmdk-convert is just for testing purposes - we use pmdk-convert tests as an additional check to validate the compatibility of new releases.
